apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-tempo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana/tempo-distributed
    targetRevision: 1.39.0
    helm:
      value: |
        distributor:
        receivers:
          otlp:
            protocols:
              grpc:

        ingester:
          trace_idle_period: 10s  
          max_block_bytes: 1_000_000  
          max_block_duration: 1m  

        compactor:
          compaction:
            compaction_window: 1h             
            max_compaction_objects: 1000000   
            block_retention: 1h
            compacted_block_retention: 10m
            flush_size_bytes: 5242880 

        storage:
          trace:
            backend: s3
            s3:
              access_key: 'grafana-tempo'
              secret_key: 'supersecret'
              bucket: 'tempo-traces'
              endpoint: 'tempo-minio:9000'
              insecure: true

        minio:
          enabled: true
          mode: standalone
          rootUser: grafana-tempo
          rootPassword: supersecret
          buckets:
            - name: tempo-traces
              policy: none
              purge: false

  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
