distributor:
  receivers:
    otlp:
      protocols:
        grpc:

ingester:
  trace_idle_period: 10s  
  max_block_bytes: 1_000_000  
  max_block_duration: 1m  

compactor:
  compaction:
    compaction_window: 1h             
    max_compaction_objects: 1000000   
    block_retention: 1h
    compacted_block_retention: 10m
    flush_size_bytes: 5242880 

storage:
  trace:
    backend: s3
    s3:
      access_key: your-civo-objectstore-access-key
      secret_key: your-civo-objectstore-secret-key
      endpoint: your-civo-objectstore-endpoint
      bucket: tempo # Replace this with the actual name of your civo object store
      insecure: true