adminUser: admin
adminPassword: admin

persistence:
  enabled: true
  storageClassName: ""
  size: 5Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        url: http://grafana-tempo:3100
        isDefault: true
        editable: true